<?php
require __DIR__.'/vendor/autoload.php';
$app = require_once __DIR__.'/bootstrap/app.php';
$app->make(\Illuminate\Contracts\Console\Kernel::class)->bootstrap();

use App\Models\Course;
use App\Models\Lesson;

// Disable FK checks, truncate, re-enable
\Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS=0');
Lesson::truncate();
\Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS=1');

// Get course IDs
$eduCourse  = Course::where('category', 'education')->first();
$techCourse = Course::where('category', 'technical')->first();
$psyCourse  = Course::where('category', 'psychology')->first();

// ── FOOTBALL EDUCATION COURSE ─────────────────────────────────────────────────
$eduLessons = [
  [1, 'The Laws of the Game', 'both', '20 mins', 'beginner', 'bi-book-fill',
   "Understanding the 17 Laws of Football is essential for every player and coach.\n\n**The 17 Laws:**\n1. The Field of Play — dimensions, markings, goals\n2. The Ball — size, weight, pressure\n3. The Players — 11 per team, goalkeeper rules\n4. The Players' Equipment — boots, shin guards, no jewellery\n5. The Referee — authority, decisions are final\n6. The Other Match Officials — assistant referees, VAR\n7. The Duration of the Match — 90 minutes, two halves\n8. The Start and Restart of Play — kick-off, dropped ball\n9. The Ball In and Out of Play — when play stops\n10. Determining the Outcome — goals, extra time, penalties\n11. Offside — position, involvement in play\n12. Fouls and Misconduct — direct/indirect free kicks, cards\n13. Free Kicks — direct vs indirect\n14. The Penalty Kick — spot, run-up, goalkeeper position\n15. The Throw-In — technique, position\n16. The Goal Kick — from goal area\n17. The Corner Kick — from corner arc\n\n**Key Rule for Players:** You are offside if you are nearer to the opponent's goal line than both the ball and the second-last opponent when the ball is played to you.\n\n**Key Rule for Coaches:** Understanding Laws 12 (Fouls) and 11 (Offside) helps you design training that avoids unnecessary stoppages and exploits tactical advantages."],

  [2, 'Football Ethics & Fair Play', 'both', '15 mins', 'beginner', 'bi-shield-check',
   "Football is more than a game — it is a platform for character development.\n\n**Core Principles of Fair Play:**\n- **Respect** — for opponents, referees, teammates, and the game itself\n- **Integrity** — playing honestly, no diving, no time-wasting\n- **Inclusion** — welcoming players of all backgrounds, abilities, and genders\n- **Responsibility** — taking ownership of your actions on and off the pitch\n\n**For Players:**\nAlways shake hands before and after a match. Accept referee decisions without argument. Help an injured opponent. Celebrate goals with respect — no taunting.\n\n**For Coaches:**\nModel the behaviour you want to see. Never instruct players to foul deliberately. Praise effort over results. Create a safe, inclusive training environment. The FIFA Fair Play Code states: 'Play to win but accept defeat with dignity.'\n\n**OFA Values in Action:**\nAt Olufunke Football Academy, we believe that how you play defines who you are. Our players are trained to be champions in character first, football second."],

  [3, 'Teamwork & Leadership on the Pitch', 'both', '20 mins', 'intermediate', 'bi-people-fill',
   "Great teams are built on communication, trust, and shared purpose.\n\n**The 5 Pillars of Team Cohesion:**\n1. **Communication** — verbal and non-verbal signals, calling for the ball, organising defence\n2. **Trust** — believing in your teammates' decisions and abilities\n3. **Roles & Responsibilities** — every player knows their job\n4. **Collective Goals** — team success over individual glory\n5. **Resilience** — bouncing back together after setbacks\n\n**Leadership Styles in Football:**\n- **Vocal Leader** — organises, motivates, communicates constantly (e.g. goalkeeper, central midfielder)\n- **Lead by Example** — works hardest in training, never gives up (e.g. striker, winger)\n- **Tactical Leader** — reads the game, makes smart decisions under pressure\n\n**For Players — Practical Tips:**\n- Always communicate your position: 'Man on!', 'Turn!', 'Time!'\n- Support teammates after mistakes — never blame\n- Celebrate assists as much as goals\n\n**For Coaches — Building Team Culture:**\n- Rotate the captain role to develop leadership across the squad\n- Use small-sided games to build communication habits\n- Debrief after every match — what did we do well as a TEAM?"],

  [4, 'Nutrition & Recovery for Footballers', 'both', '25 mins', 'intermediate', 'bi-heart-pulse-fill',
   "What you eat and how you recover directly impacts your performance on the pitch.\n\n**Pre-Match Nutrition (3-4 hours before):**\n- Complex carbohydrates: rice, pasta, yam, plantain\n- Lean protein: chicken, fish, eggs\n- Avoid: heavy fried foods, excess sugar, fizzy drinks\n- Hydrate: 500ml water 2 hours before kick-off\n\n**During the Match:**\n- Sip water at half-time (200-300ml)\n- Avoid energy drinks — they cause dehydration\n\n**Post-Match Recovery (within 30 minutes):**\n- Protein + carbs: banana + groundnuts, rice + beans\n- Rehydrate: 1.5x the fluid you lost through sweat\n- Stretch for 10-15 minutes\n\n**Sleep — The Most Powerful Recovery Tool:**\n- 8-10 hours for players aged 13-19\n- Sleep is when muscles repair and grow\n- Consistent sleep schedule improves reaction time and decision-making\n\n**For Coaches:**\n- Educate parents on pre-match meal timing\n- Schedule training sessions to allow adequate recovery\n- Monitor players who appear fatigued — rest is training too\n\n**Nigerian Foods That Fuel Performance:**\n- Oats with banana — excellent pre-training breakfast\n- Jollof rice with chicken — ideal pre-match meal\n- Zobo (hibiscus drink) — natural antioxidant for recovery"],

  [5, 'Injury Prevention & First Aid Basics', 'both', '20 mins', 'beginner', 'bi-bandaid-fill',
   "Preventing injuries is as important as developing skills.\n\n**The Warm-Up — FIFA 11+ Protocol:**\nThe FIFA 11+ is a complete warm-up programme proven to reduce injuries by up to 50%.\n\nPhase 1 — Running Exercises (8 minutes):\n- Jogging in a straight line\n- Hip out/in rotation\n- Circling partner\n- Jumping with hip rotation\n- Quick forward/backward runs\n\nPhase 2 — Strength, Plyometrics & Balance (10 minutes):\n- Nordic hamstring curls\n- Single-leg balance\n- Squats\n- Jumping lunges\n\nPhase 3 — Running Exercises (2 minutes):\n- Bounding strides\n- Plant and cut movements\n\n**Most Common Football Injuries:**\n1. Ankle sprains — RICE: Rest, Ice, Compression, Elevation\n2. Hamstring strains — stop play immediately, no stretching\n3. Knee injuries (ACL) — requires medical attention\n4. Shin splints — reduce training load, ice after sessions\n5. Head injuries — NEVER return to play same day\n\n**For Coaches — First Aid Essentials:**\n- Always have a first aid kit at training\n- Know the signs of concussion: headache, confusion, dizziness\n- Have emergency contact numbers for all players\n- Never pressure an injured player to continue"],
];

foreach ($eduLessons as $l) {
    Lesson::create(['course_id' => $eduCourse->id, 'order' => $l[0], 'title' => $l[1],
        'target_audience' => $l[2], 'duration' => $l[3], 'difficulty' => $l[4], 'icon' => $l[5], 'content' => $l[6]]);
}
echo "Education lessons: " . count($eduLessons) . "\n";

// ── TECHNICAL TRAINING COURSE ─────────────────────────────────────────────────
$techLessons = [
  [1, 'Ball Mastery & First Touch', 'both', '30 mins', 'beginner', 'bi-circle-fill',
   "Ball mastery is the foundation of all technical ability in football.\n\n**What is Ball Mastery?**\nThe ability to control the ball in any situation — under pressure, at speed, in tight spaces — using all surfaces of the foot.\n\n**Key Surfaces of the Foot:**\n- Inside foot — most accurate for passing and control\n- Outside foot — used for disguised passes and dribbling\n- Sole — used for rolling, shielding, and quick direction changes\n- Instep (laces) — used for shooting and long passes\n- Heel — used for back-heels and flicks\n\n**Ball Mastery Drills (10 minutes daily):**\n1. **Toe Taps** — alternate tapping the top of the ball with each foot, 30 seconds\n2. **Inside-Outside Rolls** — roll ball with inside, then outside of same foot\n3. **V-Pull** — pull ball back with sole, push forward with inside foot\n4. **Scissors** — step over the ball with one foot, push away with the other\n5. **Cruyff Turn** — fake to pass/shoot, drag ball behind standing leg\n\n**First Touch Principles:**\n- Cushion the ball — don't let it bounce away\n- Take the touch away from pressure\n- Set yourself for the next action (pass, shoot, dribble)\n- Use your body as a shield when receiving under pressure\n\n**For Coaches — Session Design:**\nSpend 10-15 minutes of every session on ball mastery. Use music to keep energy high. Progress from stationary to moving to under pressure. The FIFA Technical Activation protocol recommends high-frequency, high-volume repetition for skill acquisition."],

  [2, 'Passing & Receiving', 'both', '30 mins', 'beginner', 'bi-arrow-left-right',
   "Passing is the language of football. Master it and you control the game.\n\n**Types of Passes:**\n1. **Short Pass (Inside Foot)** — most accurate, used in tight spaces\n   - Plant foot beside the ball, toe pointing at target\n   - Strike through the middle of the ball\n   - Follow through toward target\n\n2. **Long Pass (Instep/Laces)** — used to switch play, find forwards\n   - Approach at slight angle\n   - Plant foot 15-20cm beside ball\n   - Strike through bottom half for height\n\n3. **Through Ball** — played into space behind the defence\n   - Weight is critical — too hard = goalkeeper, too soft = offside trap\n   - Disguise your intention before playing it\n\n4. **Back-Heel** — used to surprise opponents\n5. **Chip Pass** — used to play over a pressing defender\n\n**Receiving Principles:**\n- Scan before the ball arrives — know where you'll play next\n- Open your body to receive across the pitch\n- Take your first touch away from pressure\n- Communicate: 'Yes!', 'Turn!', 'Man on!'\n\n**Passing Drills:**\n- **Rondo (4v1, 5v2)** — keep possession in a circle, develop quick passing\n- **Pass and Move** — always move after passing, no standing still\n- **Triangle Passing** — 3 players, 2 touches maximum\n\n**For Coaches:**\nThe rondo is the most effective passing drill in football. Used by Barcelona, Ajax, and all elite academies. Start with 4v1, progress to 5v2, then directional rondos. Key coaching points: weight of pass, angle of support, communication."],

  [3, 'Shooting & Finishing', 'player', '30 mins', 'intermediate', 'bi-bullseye',
   "Goals win games. Clinical finishing separates good players from great ones.\n\n**Types of Shots:**\n1. **Instep Drive (Power Shot)**\n   - Approach at 30-45 degree angle\n   - Plant foot beside the ball, toe pointing at goal\n   - Strike through the centre with laces\n   - Follow through — don't stop your leg\n   - Keep head down, eyes on ball at moment of contact\n\n2. **Side-Foot Finish (Placement)**\n   - Used inside the box for accuracy\n   - Strike with inside of foot\n   - Pick your corner — goalkeeper's near post or far post\n\n3. **Volley**\n   - Keep eyes on the ball\n   - Strike through the centre\n   - Lean slightly back for height, forward to keep it down\n\n4. **Header**\n   - Attack the ball — don't wait for it\n   - Use forehead, not top of head\n   - Eyes open, mouth closed\n   - Generate power from neck and upper body\n\n**Finishing Principles:**\n- Shoot early — goalkeepers hate early shots\n- Pick your spot before the ball arrives\n- Stay calm — slow your breathing\n- If in doubt, hit the target\n\n**Shooting Drills:**\n- **1v1 with Goalkeeper** — develop composure in front of goal\n- **Crossing and Finishing** — movement, timing, different angles\n- **Rebound Finishing** — react to parried shots\n\n**For Coaches:**\nCreate shooting drills that replicate match situations. Always include a defender or time pressure. Track goals-to-shots ratio in training to measure improvement."],

  [4, 'Dribbling & 1v1 Skills', 'player', '25 mins', 'intermediate', 'bi-lightning-fill',
   "Dribbling is the ability to beat an opponent and create space. It is one of the most exciting skills in football.\n\n**Principles of Effective Dribbling:**\n1. **Keep the ball close** — no more than 1-2 touches ahead\n2. **Use your body** — shoulder drops, head fakes, change of pace\n3. **Protect the ball** — use your body as a shield\n4. **Know when to dribble** — not in your own penalty area\n5. **Have an exit plan** — know where you'll go after beating the defender\n\n**Essential Dribbling Moves:**\n\n**Step Over (Ronaldo Chop)**\n- Step over the ball with one foot\n- Push away with the outside of the other foot\n- Accelerate past the defender\n\n**Elastico (Flip-Flap)**\n- Push ball outside with outside of foot\n- Immediately flick inside with inside of same foot\n- Requires quick feet and close control\n\n**Maradona Turn (360)**\n- Sole roll forward with one foot\n- Drag back with other foot\n- Turn 180 degrees away from defender\n\n**Shoulder Drop**\n- Drop one shoulder to fake direction\n- Push ball the other way\n- Accelerate into space\n\n**1v1 Defending (For Defenders):**\n- Stay on your feet — don't dive in\n- Force the attacker onto their weak foot\n- Delay until support arrives\n- Win the ball when the attacker's touch is heavy\n\n**For Coaches:**\nUse 1v1 corridors to develop dribbling under pressure. Progress from no defender → passive defender → active defender. Reward creativity — let players try new moves without fear of failure."],

  [5, 'Tactical Awareness & Positioning', 'both', '35 mins', 'advanced', 'bi-diagram-3-fill',
   "Understanding the game tactically separates intelligent players from instinctive ones.\n\n**The 4 Phases of the Game:**\n1. **In Possession** — what do we do when we have the ball?\n2. **Out of Possession** — how do we defend as a team?\n3. **Transition to Attack** — winning the ball and going forward quickly\n4. **Transition to Defence** — losing the ball and pressing immediately\n\n**Positional Play Principles:**\n- **Width** — stretch the opposition by using the full width of the pitch\n- **Depth** — create passing options in front and behind the ball\n- **Triangles** — always create triangles of support around the ball carrier\n- **Third Man Runs** — the player who doesn't receive the pass makes a run\n\n**Defensive Organisation:**\n- **Compact shape** — reduce space between lines\n- **Press triggers** — when to press (bad touch, back pass, goalkeeper)\n- **Cover and balance** — one player presses, others cover\n- **Defensive line** — push up to compress space, drop to protect\n\n**Common Formations:**\n- **4-3-3** — attacking, wide, requires high-energy wingers\n- **4-4-2** — balanced, good defensive shape, requires two hard-working strikers\n- **4-2-3-1** — modern, double pivot protects defence, number 10 creates\n- **3-5-2** — wing-backs provide width, strong in midfield\n\n**For Coaches — Session Design:**\nUse positional games (rondos with goals) to teach tactical concepts. Shadow play (no opposition) to rehearse shape and movement. Small-sided games (5v5, 7v7) to apply tactical principles in realistic scenarios.\n\n**OFA Playing Philosophy:**\nOlufunke FA plays a possession-based, high-pressing style. Players are expected to press immediately after losing the ball and build from the back with confidence."],

  [6, 'Set Pieces — Attacking & Defending', 'both', '25 mins', 'advanced', 'bi-flag-fill',
   "Up to 30% of goals in football come from set pieces. Mastering them gives your team a massive advantage.\n\n**Corner Kicks — Attacking:**\n- **Near Post Run** — attacker attacks the near post to flick on\n- **Far Post Run** — attacker attacks the far post for a header\n- **Penalty Spot Run** — attacker arrives late at the penalty spot\n- **Short Corner** — play short to create a crossing angle\n- **Inswinger vs Outswinger** — inswinger causes chaos, outswinger allows attackers to attack the ball\n\n**Corner Kicks — Defending:**\n- Zonal marking: players defend zones, not men\n- Man marking: each defender marks a specific attacker\n- Hybrid: zonal at near post, man-marking at far post\n- Always have a player on each post\n\n**Free Kicks — Attacking:**\n- **Direct Shot** — power and placement over the wall\n- **Dummy Run** — one player runs over the ball, another shoots\n- **Layoff** — short pass to a runner arriving late\n- **Chip over wall** — for free kicks 25-30 yards out\n\n**Free Kicks — Defending:**\n- Wall of 3-5 players, 9.15m from ball\n- Goalkeeper organises the wall\n- One player in wall watches for short free kick\n- Remaining defenders mark runners\n\n**Throw-Ins:**\n- Long throw-in near the box is a dangerous weapon\n- Short throw-in to maintain possession\n- Always have a second option\n\n**For Coaches:**\nDedicate 10-15 minutes per week to set piece rehearsal. Keep routines simple — 2-3 attacking corners, 1-2 free kick routines. Repetition builds confidence and execution."],
];

foreach ($techLessons as $l) {
    Lesson::create(['course_id' => $techCourse->id, 'order' => $l[0], 'title' => $l[1],
        'target_audience' => $l[2], 'duration' => $l[3], 'difficulty' => $l[4], 'icon' => $l[5], 'content' => $l[6]]);
}
echo "Technical lessons: " . count($techLessons) . "\n";

// ── SPORTS PSYCHOLOGY COURSE ──────────────────────────────────────────────────
$psyLessons = [
  [1, 'The Mental Game — Introduction to Sports Psychology', 'both', '20 mins', 'beginner', 'bi-brain',
   "Elite performance is 50% physical and 50% mental. Sports psychology gives you the tools to unlock your full potential.\n\n**What is Sports Psychology?**\nSports psychology is the study of how psychological factors affect performance and how participation in sport affects psychological and physical factors.\n\n**The 5 Core Mental Skills:**\n1. **Confidence** — believing in your ability to succeed\n2. **Focus** — directing attention to what matters most\n3. **Motivation** — the drive to train hard and compete\n4. **Emotional Control** — managing anxiety, frustration, and pressure\n5. **Resilience** — bouncing back from setbacks and mistakes\n\n**The Performance Zone:**\nEvery player has an optimal arousal level for peak performance. Too relaxed = underperformance. Too anxious = overperformance. Finding your zone is the goal.\n\n**For Players:**\nThink about your best ever performance. How did you feel? Confident? Relaxed? Focused? That was your performance zone. Sports psychology helps you get there consistently.\n\n**For Coaches:**\nUnderstanding your players' mental states is as important as understanding their technical ability. A player who is anxious, distracted, or low in confidence will underperform regardless of their physical ability.\n\n**OFA Mental Performance Commitment:**\nAt Olufunke Football Academy, we develop the whole player — mind, body, and character. Mental skills training is integrated into every training session."],

  [2, 'Building Confidence & Self-Belief', 'both', '25 mins', 'beginner', 'bi-star-fill',
   "Confidence is not something you either have or don't have — it is a skill you can build.\n\n**What is Confidence in Football?**\nThe belief that you can execute a skill, make a decision, or perform under pressure successfully.\n\n**Sources of Confidence:**\n1. **Past Performance** — remembering your best moments\n2. **Preparation** — knowing you've trained hard\n3. **Physical State** — feeling fit, strong, and ready\n4. **Social Support** — encouragement from coaches, teammates, family\n5. **Self-Talk** — what you say to yourself\n\n**Positive Self-Talk Techniques:**\n- Replace 'I can't' with 'I will'\n- Replace 'I always miss penalties' with 'I've scored penalties before and I will again'\n- Use cue words: 'Strong', 'Sharp', 'Calm', 'Ready'\n- Pre-match affirmations: 'I am prepared. I am capable. I will compete.'\n\n**The Confidence Cycle:**\nPreparation → Performance → Success → Confidence → Better Preparation\n\n**For Players — Confidence Builders:**\n- Keep a 'highlight reel' in your mind of your best moments\n- Set small, achievable goals in training\n- Celebrate small wins — a good first touch, a successful tackle\n- Don't compare yourself to others — compare yourself to yesterday's version of you\n\n**For Coaches — Building Player Confidence:**\n- Praise effort and process, not just results\n- Give players roles that match their current ability level\n- Create training environments where mistakes are learning opportunities\n- Use the 'sandwich' feedback method: positive → improvement → positive"],

  [3, 'Focus & Concentration Under Pressure', 'both', '25 mins', 'intermediate', 'bi-eye-fill',
   "The ability to focus under pressure is what separates good players from great ones.\n\n**Types of Focus in Football:**\n1. **Broad External** — scanning the whole pitch, reading the game\n2. **Narrow External** — focusing on the ball, a specific opponent\n3. **Broad Internal** — thinking about tactics, game plan\n4. **Narrow Internal** — focusing on your breathing, body sensations\n\n**Common Focus Disruptors:**\n- Crowd noise and abuse\n- Referee decisions\n- Mistakes (your own or teammates')\n- Score line\n- Fatigue\n- Negative self-talk\n\n**Refocusing Techniques:**\n\n**The 3R Process:**\n1. **Recognise** — notice you've lost focus\n2. **Release** — let go of the distraction (deep breath, physical cue)\n3. **Refocus** — return attention to the next action\n\n**Physical Cues:**\n- Clap your hands once to reset\n- Touch your wristband or captain's armband\n- Take a deep breath and exhale slowly\n- Look at the ball — the ball is always in the present moment\n\n**Pre-Performance Routines:**\nElite players use consistent routines before penalties, free kicks, and throw-ins to trigger focus. Develop your own routine: 3 deep breaths, visualise the action, execute.\n\n**For Coaches:**\nCreate training environments with distractions (noise, pressure, consequences) to build focus under pressure. Debrief players on their focus after matches — not just their physical performance."],

  [4, 'Managing Anxiety & Pre-Match Nerves', 'both', '20 mins', 'intermediate', 'bi-heart-fill',
   "Nerves are normal. Every elite athlete experiences them. The key is using them as fuel, not letting them become fear.\n\n**Understanding Anxiety in Sport:**\nAnxiety is your body's natural response to a perceived threat or challenge. In football, it manifests as:\n- Butterflies in the stomach\n- Increased heart rate\n- Sweaty palms\n- Negative thoughts ('What if I miss?')\n- Muscle tension\n\n**Reframing Anxiety:**\nResearch shows that telling yourself 'I am excited' rather than 'I am nervous' improves performance. Both states feel similar physically — the difference is your interpretation.\n\n**Breathing Techniques:**\n\n**Box Breathing (4-4-4-4):**\n1. Inhale for 4 counts\n2. Hold for 4 counts\n3. Exhale for 4 counts\n4. Hold for 4 counts\nRepeat 4 times. This activates the parasympathetic nervous system and reduces anxiety.\n\n**Progressive Muscle Relaxation:**\nTense each muscle group for 5 seconds, then release. Start from feet, work up to face. Releases physical tension before matches.\n\n**Pre-Match Routine for Players:**\n- Arrive early — rushing increases anxiety\n- Warm up properly — physical activity reduces anxiety\n- Listen to your favourite music\n- Use positive self-talk\n- Focus on what you can control (your effort, your attitude)\n\n**For Coaches:**\nCreate a calm, positive pre-match environment. Avoid overloading players with tactical information in the final minutes. Use humour to reduce tension. Remind players of their preparation and capability."],

  [5, 'Resilience — Bouncing Back from Setbacks', 'both', '25 mins', 'intermediate', 'bi-arrow-repeat',
   "Every footballer faces setbacks — missed penalties, bad form, injuries, defeats. Resilience is what keeps you going.\n\n**What is Resilience?**\nThe ability to adapt positively in the face of adversity, trauma, tragedy, threats, or significant sources of stress.\n\n**The 4 Components of Resilience:**\n1. **Emotional Regulation** — managing your emotional response to setbacks\n2. **Optimism** — believing things will improve\n3. **Self-Efficacy** — confidence in your ability to overcome challenges\n4. **Social Support** — leaning on teammates, coaches, family\n\n**The Resilience Response Model:**\nSetback → Emotional Response → Reflection → Learning → Growth\n\n**For Players — After a Bad Game:**\n- Allow yourself 24 hours to feel disappointed — it's healthy\n- After 24 hours, shift to learning mode: What can I improve?\n- Write down 3 things you did well and 1 thing to work on\n- Return to training with renewed purpose\n- Remember: Every elite player has had bad games. Messi missed penalties. Ronaldo had poor seasons.\n\n**For Players — After an Injury:**\n- Focus on what you CAN do, not what you can't\n- Use recovery time to study the game, improve mentally\n- Set small daily goals for rehabilitation\n- Stay connected to the team\n\n**For Coaches — Building Resilient Players:**\n- Create training environments where failure is safe\n- Debrief after defeats — focus on learning, not blame\n- Share stories of elite players who overcame adversity\n- Develop a 'growth mindset' culture: ability is developed through effort\n\n**OFA Resilience Mantra:**\n'We fall, we learn, we rise. Every setback is a setup for a comeback.'"],

  [6, 'Goal Setting & Motivation', 'both', '20 mins', 'beginner', 'bi-trophy-fill',
   "Clear goals give you direction, purpose, and the motivation to keep working when it gets hard.\n\n**The SMART Goal Framework:**\n- **S**pecific — exactly what do you want to achieve?\n- **M**easurable — how will you know when you've achieved it?\n- **A**chievable — is it realistic given your current level?\n- **R**elevant — does it align with your bigger football goals?\n- **T**ime-bound — when will you achieve it?\n\n**Example SMART Goals:**\n\nPlayer: 'I will improve my weak foot by practising 50 passes with my left foot every day for the next 4 weeks.'\n\nCoach: 'I will complete the CAF C Coaching Licence by December 2026 by studying 3 hours per week.'\n\n**Types of Goals:**\n1. **Outcome Goals** — winning the league, scoring 10 goals (motivating but not fully in your control)\n2. **Performance Goals** — completing 80% of passes, winning 60% of headers (measurable, in your control)\n3. **Process Goals** — scanning before receiving, pressing within 3 seconds of losing the ball (daily habits)\n\n**The Goal Ladder:**\nLong-term dream → Medium-term goals → Short-term weekly goals → Daily habits\n\n**Motivation Types:**\n- **Intrinsic** — playing because you love it (most powerful, most sustainable)\n- **Extrinsic** — playing for rewards, recognition (useful short-term)\n\n**For Coaches:**\nSet individual goals with each player at the start of the season. Review monthly. Celebrate progress, not just achievement. Help players connect their daily training to their long-term dreams.\n\n**OFA Goal-Setting Session:**\nEvery OFA player sets 3 goals at the start of each season: 1 technical, 1 physical, 1 personal development goal. These are reviewed monthly with their coach."],

  [7, 'Mindfulness & Visualisation for Peak Performance', 'both', '25 mins', 'advanced', 'bi-eye',
   "The world's best footballers use visualisation and mindfulness to prepare mentally for peak performance.\n\n**What is Visualisation?**\nCreating a vivid mental image of successfully performing a skill or action before you physically do it. Used by Cristiano Ronaldo, Lionel Messi, and virtually every elite athlete.\n\n**How to Visualise Effectively:**\n1. Find a quiet space, close your eyes\n2. Take 5 deep breaths to relax\n3. Picture yourself in the specific situation (penalty kick, 1v1, corner kick)\n4. See it in first person — through your own eyes\n5. Include all senses: see the goal, hear the crowd, feel the ball\n6. Visualise the perfect execution — the ball hitting the net\n7. Feel the emotion of success\n8. Repeat 3-5 times\n\n**Visualisation for Different Situations:**\n- **Before a penalty** — see your run-up, your contact, the ball in the net\n- **Before a match** — see yourself making key tackles, passes, runs\n- **During injury recovery** — visualise the injured area healing, yourself returning to play\n\n**Mindfulness in Football:**\nMindfulness is the practice of being fully present in the current moment — not thinking about the last mistake or the next match, but fully engaged in what is happening right now.\n\n**Simple Mindfulness Practice:**\n- Before training, take 2 minutes to focus only on your breathing\n- During training, notice the feel of the ball, the sound of your boots\n- After training, reflect on 3 things you did well\n\n**For Coaches:**\nIntroduce 2-minute mindfulness breathing at the start of training sessions. Use visualisation as part of set-piece preparation. Encourage players to develop pre-performance routines."],
];

foreach ($psyLessons as $l) {
    Lesson::create(['course_id' => $psyCourse->id, 'order' => $l[0], 'title' => $l[1],
        'target_audience' => $l[2], 'duration' => $l[3], 'difficulty' => $l[4], 'icon' => $l[5], 'content' => $l[6]]);
}
echo "Psychology lessons: " . count($psyLessons) . "\n";

// Update course descriptions
Course::where('category','education')->update([
    'description' => 'Master the Laws of the Game, football ethics, teamwork, nutrition, and injury prevention. 5 comprehensive lessons for players and coaches.',
    'cta_label'   => 'Start Learning',
]);
Course::where('category','technical')->update([
    'description' => 'Develop ball mastery, passing, shooting, dribbling, tactical awareness, and set pieces. 6 expert-led modules aligned with FIFA standards.',
    'cta_label'   => 'Start Training',
]);
Course::where('category','psychology')->update([
    'description' => 'Build confidence, focus, resilience, and mental toughness. 7 evidence-based modules for players and coaches to unlock peak performance.',
    'cta_label'   => 'Start Module',
]);

echo "Courses updated.\n";
echo "Total lessons: " . Lesson::count() . "\n";
echo "\nDone!\n";
